### ISSUE TITLE
Making all class members private

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/graybat#116]
Imho class members like "hostedVertices" of [Cage](https://computationalradiationphysics.github.io/graybat/structgraybat_1_1Cage.html) should not be accessible from the outside -- especially as getters and setters already exist.

Consequently the examples using the member should be changed, too.

**Comment by erikzenker** [comment]
The reason for accessing them directly was pure lazyness from my side. But, you are right. I will work on that in the next days and provide a pull request. Would you like to support me in the review process ?

**Comment by theZiz** [comment]
Yeah, I guess this makes sense. I put it on my ToDo for tuesday ;)

**Comment by erikzenker** [comment]
I provided a PR for this issue (See #117).
