### ISSUE TITLE
Elegant Progressbars broken

### ISSUE THREAD

**Issue by fabian-jung** [ComputationalRadiationPhysics/graybat#119]
The output for the testsuits is broken on bash, zsh and fish. It is mainly a cosmetic problem, since the tests complete normal.

**Comment by erikzenker** [comment]
Boost test can also print progress with the option `--show_progress=true`. We could replace the elegant progressbar by that.

**Comment by erikzenker** [comment]
Just for the interest, what exactly is broken? Can you copy the output to show me how it looks on your shell?

**Comment by erikzenker** [comment]
Solved in #120.
