### ISSUE TITLE
CommunicationPolicy: ZeroMQ

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/graybat#20]
ZeroMQ is a quite interesting communication library with implementations in IPC, TCP, TIPC, multicast, ...

Probably, several of the implemented functionalities would be interesting, independently each as a `CommunicationPolicy`.

GitHub: https://github.com/zeromq
Homepage: http://zeromq.org/

**Comment by erikzenker** [comment]
ZeroMQ provides three high level C++ Bindings:
1. [CPPZMQ - The standard bindings (ZMQ 3.0)](https://github.com/zeromq/cppzmq)
2. [AZMQ - Boost Asio style bindings (ZMQ 4.0)](https://github.com/zeromq/azmq)
3. [ZMQPP -  Just another binding (ZMQ 3.0)](https://github.com/zeromq/zmqpp)

As a fan of the the boost library i would like to have a look at AZMQ first.

**Comment by ax3l** [comment]
pfff... fanboy ;)
boost asio pulls quite some dependencies but why not, it's pretty neat.

**Comment by erikzenker** [comment]
Do you have experience with the other bindings ? It seems that
the other ones do not support ZMQ 4.0 yet. Otherwise i do not
know the difference between 3.0 und 4.0 yet :roller_coaster:

**Comment by ax3l** [comment]
unfurtunately I did not experiment with ZMQ bindings yet outside of ipython notebook.
I used asio to write a unix signal handler (not finished) some month ago: https://github.com/ax3l/picongpu/commits/topic/signals

**Comment by bussmann** [comment]
We use Boost often and the wrapper seems well maintained, so why not?

**Comment by ax3l** [comment]
It's not a question of not to use, it's just worth mentioning that asio pulls in a huge amount of [dependencies](http://www.boost.org/doc/libs/1_58_0/doc/html/boost_asio/using.html) in boost alone (at least [pre-compiled `thread` and `system`).

Just because something is in boost does not declare it "well maintained". Each subproject has it's own maintainers and we simply have just very little experience with asio. I just recommend to try to compile boost with "-all" enabled to see what I mean.

**Update:** even the azmq "asio style bindings" [repo](https://github.com/zeromq/azmq) has only 181 commits from effectively 2 developers and 0 releases, being developed since less than half a year...

**Comment by bussmann** [comment]
Yeah, I know Boost is a mess. I think we habe to evaluate this further, then.

**Comment by ax3l** [comment]
well I think he can try both, just be aware it's not an official boost library and might eat your cat.

imho boost is pretty well organized and does peer reviews. a small problem is that some projects run out of maintainers from time to time and not all libs seem to be covered with exhaustive CI tests.

**Comment by erikzenker** [comment]
Finally i used the standard zmq bindings, but I will have a look into the other bindings in the future just because of interest.

**Comment by erikzenker** [comment]
Its on the way. I had some issues with storing messages in concurrent queues, but solved that problem the last days hopefully :smiley:

**Comment by ax3l** [comment]
that's rly awesome :)
