### ISSUE TITLE
Mapping based on graph partitioning

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/graybat#21]
[Graph partitioning](http://en.wikipedia.org/wiki/Graph_partition) is the perfect tool to map
a graph to a set of peers. A full framework is provided by [Metis](http://glaros.dtc.umn.edu/gkhome/views/metis). Should not be to complex to include in graybat as a mapping functor.

**Comment by erikzenker** [comment]
Tested metis and it worked after 10 minutes of hard work :crying_cat_face: 

The following steps were necessary:
- Download and install [Metis](http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz)
- Read into [Metis API documentation](http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/manual.pdf)
- Write some [example](https://gist.github.com/erikzenker/c4dc42c8d5a8c1cd3e5a)

Next step is the implementation of some mapping functor prototype

**Comment by bussmann** [comment]
Be happy on the outside while crying on the inside.
