### ISSUE TITLE
Signaling server should get uri by package meta data instead content

### ISSUE THREAD

**Issue by fabian-jung** [ComputationalRadiationPhysics/graybat#53]

**Comment by erikzenker** [comment]
A post on [stackoverflow](http://stackoverflow.com/questions/20336954/0mq-get-message-ip) says that the ip of a zmq message can`t be exposed.

**Comment by erikzenker** [comment]
Some solution [here](http://lists.zeromq.org/pipermail/zeromq-dev/2010-September/006381.html)

**Comment by erikzenker** [comment]
Another reason to not obtain the uri from the signaling server is that the zmq peers could connect by inter process sockets with each other but the signaling server is reachable by tcp sockets. If you don't have other reasons for this issue then I would like to close it.
