### ISSUE TITLE
Compiler warnings g++ 5.2.0

### ISSUE THREAD

**Issue by fabian-jung** [ComputationalRadiationPhysics/graybat#58]
In file included from /home/fabian/DSP/include/graybat/include/graybat/utils/hana/include/boost/hana.hpp:50:0,
                 from /home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:24,
                 from /home/fabian/DSP/src/Input/GrayBatReader.hpp:8,
                 from /home/fabian/DSP/src/Fitter.cpp:3:
/home/fabian/DSP/include/graybat/include/graybat/utils/hana/include/boost/hana/config.hpp:52:5: Warnung: #warning "You appear to be using GCC, which is not supported by Hana yet." [-Wcpp]
 #   warning "You appear to be using GCC, which is not supported by Hana yet."
     ^
In file included from /home/fabian/DSP/src/Input/GrayBatReader.hpp:8:0,
                 from /home/fabian/DSP/src/Fitter.cpp:3:
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp: In Konstruktor »graybat::communicationPolicy::ZMQ::ZMQ(std::string, std::string, unsigned int)«:
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:175:15: Warnung: »graybat::communicationPolicy::ZMQ::maxMsgID« wird initialisiert nach [-Wreorder]
      unsigned maxMsgID;
               ^
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:165:16: Warnung:   »const int graybat::communicationPolicy::ZMQ::zmqHwm« [-Wreorder]
      const int zmqHwm;
                ^
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:184:6: Warnung:   während es hier initialisiert wurde [-Wreorder]
      ZMQ(const std::string masterUri,
      ^
In file included from /home/fabian/DSP/src/Input/GrayBatReader.hpp:8:0,
                 from /home/fabian/DSP/src/Fitter.cpp:3:
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp: In statischer Elementfunktion »static char\* graybat::communicationPolicy::ZMQ::s_recv(zmq::socket_t&)«:
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:332:22: Warnung: Vergleich zwischen vorzeichenbehafteten und vorzeichenlosen Ganzzahlausdrücken [-Wsign-compare]
   if (message.size() == -1)
                      ^
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp: In Elementfunktion »graybat::communicationPolicy::ZMQ::Uri graybat::communicationPolicy::ZMQ::getUri(zmq::socket_t&, graybat::communicationPolicy::ZMQ::ContextID, graybat::communicationPolicy::ZMQ::VAddr)«:
/home/fabian/DSP/include/graybat/include/graybat/communicationPolicy/ZMQ.hpp:323:6: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
      }

**Comment by erikzenker** [comment]
fixed in #59
