### ISSUE TITLE
Uniform data transfer format

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/graybat#67]
ZMQ and BMPI have slightly different demands on the data. 
- ZMQ send data as a blob and does not care about data types.
- BMPI serializes complex data types with boost::serialize and
  primitive data types are send using the MPI primitive types.

**Comment by fabian-jung** [comment]
+1

**Comment by erikzenker** [comment]
I will add a new policy called serialization policy. Thus, the user can control how its input data should be serialized (or not). Forcing each input data to be serialized reduces bandwidth dramatically (the boost mpi team evaluated some [benchmarks](http://www.boost.org/doc/libs/1_62_0/doc/html/mpi/python.html#mpi.performance)). I have several implementations in mind:
- NoSerialization: just forwards data to the underlying layer (should not produce overhead)
- ByteCast: Cast of input data to a byte array
- BoostSerialization: Use [boost serialize](http://www.boost.org/doc/libs/1_62_0/libs/serialization/doc/index.html)
- [MsgPack serialization](https://github.com/msgpack/msgpack)
- [Google Protocol Buffers serilization](https://developers.google.com/protocol-buffers/)

**Comment by erikzenker** [comment]
I opened a pull request to document the developement of this issus (see #123).

**Comment by erikzenker** [comment]
There exists now a serialization policy, which was merged with #123.
