### ISSUE TITLE
CI - Not Running

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/graybat#68]
Are our CI tests (drone.io) not running any more?

Can we enable those again and/or shall we use travis?

**Comment by erikzenker** [comment]
We had some issues with our dyndns server and therefore had to move to another
dyndns provider. I need to change this immediately. Thx for the hint

**Comment by ax3l** [comment]
Use https://nsupdate.info/, because it's awesome.

**Comment by erikzenker** [comment]
CI is running again! :running:
