### ISSUE TITLE
Move from g++ to clang++

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/graybat#9]
Because of the nice error output :feelsgood:

**Comment by ax3l** [comment]
travis supports testing both - so why not add testing _both_ with drone.io :)

**Comment by erikzenker** [comment]
Good point. So there have to be some modifications
in the cmake file.

**Comment by ax3l** [comment]
oh I see what you mean. holy moly, never write [such a line](https://github.com/ComputationalRadiationPhysics/GrayBat/blob/0fc6ec7731db596dd37c80b3a6e1f4097d46c102/CMakeLists.txt#L27) :) the user and environment controls the compiler, not the cmake/configure script ;)

``` bash
export CXX=`which g++`
```

or stuff like

``` bash
CXX=`which clang` cmake ~/src/grayBat
```

**Comment by ax3l** [comment]
and what does `DO not compile with -OX with x > 1, can lead to segfaults` mean ? ;) valgrind it! :)

**Comment by erikzenker** [comment]
There was some stupid MPI failure made from some stupid programmer of this project. Thus, -03 is not
a problem anymore. You are right about this CXX issue, I hard coded that line because of some missconfiguration of some cluster in the forest (do not want to blame anyone here :space_invader:)

**Comment by ax3l** [comment]
hehe, all right.

well, you can even force the forest-cluster to work with environment vars ;)
